name: Android CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: write
  packages: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug and Run Tests
      run: |
        ./gradlew assembleDebug
        ./gradlew test

    - name: Decode Keystore
      if: github.ref_type == 'branch' && github.event_name == 'push' && github.repository == 'mrdarip/Stepy'
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/release.keystore

    - name: Build Signed Release APK
      if: github.ref_type == 'branch' && github.event_name == 'push' && github.repository == 'mrdarip/Stepy'
      env:
        KEYSTORE_FILE: release.keystore
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assembleRelease

    - name: Upload Signed Release APK artifact
      if: github.ref_type == 'branch' && github.event_name == 'push' && github.repository == 'mrdarip/Stepy'
      uses: actions/upload-artifact@v4
      with:
        name: app-release-signed-apk
        path: app/build/outputs/apk/release/*.apk

    - name: Upload Debug APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/*.apk

  deploy:
    name: Deploy to GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' && github.event_name == 'push' && github.repository == 'mrdarip/Stepy'
    steps:
    - name: Download Signed APK artifact
      uses: actions/download-artifact@v4
      with:
        name: app-release-signed-apk
        path: ./release-apk

    - name: Create/Update GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: Nightly
        name: ${{ github.ref_name }} - ${{ github.event.head_commit.message }}
        files: ./release-apk/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}